       module.exports = { 
     CREATE_ACCOUNT_FAILED_PSEUDO: 0,
     CREATE_ACCOUNT_FAILED_EMAIL : 1,
     CREATE_ACCOUNT_SUCCES : 2,
     ACHAT_FAILED_MDP : 3,
     ACHAT_FAILED_MONEY : 4,
     ACHAT_SUCCESS : 5,
     URL_BDD : "jdbc:mysql://217.182.69.175:3306/DropDaBomb",
     BDD_USER : "Vinspi",
     BDD_PASSWORD : "vinspi13",

     AUTH_FAILED : 6,
     AUTH_SUCCES : 7,
     AUTH_ADMIN : 30,
     SWAP_FAILED : 8,
     SWAP_SUCCESS : 9,
     UPDATE_MDP_SUCCESS : 10,
     UPDATE_EMAIL_SUCCESS : 11,
     UPDATE_MAP_SUCCESS : 12,
     UPDATE_CARTON_SUCCESS : 13,
     UPDATE_MDP_FAILED : 14,
     UPDATE_ICON_SUCCESS : 15,
     UPDATE_ICON_FAILED : 16,
     UPDATE_EMAIL_FAILED : 17,
     UPDATE_MAP_FAILED : 18,
     UPDATE_CARTON_FAILED : 19,
     UPDATE_ICON : 20,
     UPDATE_MDP : 21,
     UPDATE_EMAIL : 22,
     UPDATE_CARTON : 23,
     ACHAT_MONNAIE_SUCCESS : 24,
     ACHAT_MONNAIE_FAILED : 25,
     ACHAT_MONNAIE : 26,
     UPDATE_MAP : 27,
     ERR_MDP : 28,
     MIN_SIZE_PASSWORD : 6,
     ERR_MDP_NOT_MATCH : 29,
     EMAIL_PATTERN : "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",

    /* definir toutes les cartes sous forme de constantes */
    CARD_BOMB_25 : 0,
    CARD_BOMB_50 : 1,
    CARD_BOMB_50_2TOUR : 2,
    CARD_BOMB_100_2TOUR : 3,
    CARD_BOUCLIER_15 : 4,
    CARD_BOUCLIER_45 : 5,
    CARD_BOUCLIER_GEN_POUDRE : 6,
    CARD_ECHANGE_FORCE : 7,
    CARD_DESENVOUTEMENT : 8,
    CARD_MELANGE : 9,

    /* fin des definitions de cartes */
    NB_MAX_SALON : 6,
    NB_MAX_PDV : 150,
    NB_CARTE_MAIN_MAX : 4,
    NB_POUDRE_PAR_TOUR : 5,
    NB_MAX_TIMER : 15,
    NB_MAX_CARTE_ACTIVE : 5

};

   
    module.exports = { 
     CREATE_ACCOUNT_FAILED_PSEUDO: 0,
     CREATE_ACCOUNT_FAILED_EMAIL : 1,
     CREATE_ACCOUNT_SUCCES : 2,
     ACHAT_FAILED_MDP : 3,
     ACHAT_FAILED_MONEY : 4,
     ACHAT_SUCCESS : 5,
     URL_BDD : "jdbc:mysql://217.182.69.175:3306/DropDaBomb",
     BDD_USER : "Vinspi",
     BDD_PASSWORD : "vinspi13",

     AUTH_FAILED : 6,
     AUTH_SUCCES : 7,
     AUTH_ADMIN : 30,
     SWAP_FAILED : 8,
     SWAP_SUCCESS : 9,
     UPDATE_MDP_SUCCESS : 10,
     UPDATE_EMAIL_SUCCESS : 11,
     UPDATE_MAP_SUCCESS : 12,
     UPDATE_CARTON_SUCCESS : 13,
     UPDATE_MDP_FAILED : 14,
     UPDATE_ICON_SUCCESS : 15,
     UPDATE_ICON_FAILED : 16,
     UPDATE_EMAIL_FAILED : 17,
     UPDATE_MAP_FAILED : 18,
     UPDATE_CARTON_FAILED : 19,
     UPDATE_ICON : 20,
     UPDATE_MDP : 21,
     UPDATE_EMAIL : 22,
     UPDATE_CARTON : 23,
     ACHAT_MONNAIE_SUCCESS : 24,
     ACHAT_MONNAIE_FAILED : 25,
     ACHAT_MONNAIE : 26,
     UPDATE_MAP : 27,
     ERR_MDP : 28,
     MIN_SIZE_PASSWORD : 6,
     ERR_MDP_NOT_MATCH : 29,
     EMAIL_PATTERN : "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",

    /* definir toutes les cartes sous forme de constantes */
    CARD_BOMB_25 : 0,
    CARD_BOMB_50 : 1,
    CARD_BOMB_50_2TOUR : 2,
    CARD_BOMB_100_2TOUR : 3,
    CARD_BOUCLIER_15 : 4,
    CARD_BOUCLIER_45 : 5,
    CARD_BOUCLIER_GEN_POUDRE : 6,
    CARD_ECHANGE_FORCE : 7,
    CARD_DESENVOUTEMENT : 8,
    CARD_MELANGE : 9,

    /* fin des definitions de cartes */
    NB_MAX_SALON : 6,
    NB_MAX_PDV : 150,
    NB_CARTE_MAIN_MAX : 4,
    NB_POUDRE_PAR_TOUR : 5,
    NB_MAX_TIMER : 15,
    NB_MAX_CARTE_ACTIVE : 5

};
